# Data Settings
phase: valid

patchify: False
learn_patch: False

guidance_method: False
dilation_rates: (1, 2, 3, 4)
# dj
vae_model: litevae-s # sd-vae or imagenet-litevae or litevae-s or tiny_vae
pickle_file_path: ./Dataset/busi/busi_train_test_names.pkl

model_weight: ./ckpt/generalizability_experiments/busi_busi/litevae_baseline/best_valid_dice_445.pth
snapshot_path: ./ckpt/generalizability_experiments/bus_busi/litevae_baseline/valid_bus_best_valid_dice
save_seg_img_path: ./ckpt/generalizability_experiments/bus_busi/litevae_baseline/best_valid_dice_predicted_masks

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# loss Settings
w_rec: 1
