# Data Settings
phase: valid

patchify: False
learn_patch: False

guidance_method: False
dilation_rates: (1, 2, 3, 4)
# dj
vae_model: sd-vae # or tiny_vae
pickle_file_path: ./Dataset/bus/bus_train_test_names.pkl

model_weight: ./ckpt/generalizability_experiments/busi_bus/sd-vae_frozen/best_model.pth
snapshot_path: ./ckpt/generalizability_experiments/busi_bus/sd-vae_frozen/valid_busi_best_model
save_seg_img_path: ./ckpt/generalizability_experiments/busi_bus/sd-vae_frozen/best_model_predicted_masks

# model_weight: ./ckpt/litevae_baseline_bus_correct_transforms/epochs_1000/checkpoints/best_model_804.pth
# snapshot_path: ./ckpt/litevae_baseline_bus_correct_transforms/epochs_1000/valid_bus_best_model
# save_seg_img_path: ./ckpt/litevae_baseline_bus_correct_transforms/epochs_1000/predicted_masks_best_model

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# loss Settings
w_rec: 1
