# Data Settings
phase: valid

patchify: False
learn_patch: False

guidance_method: False
dilation_rates: (1, 2, 3, 4)
# fj
vae_model: sd-vae # or tiny_vae
pickle_file_path: ./Dataset/kvasir-instrument/kvasir-instrument_train_test_names.pkl

# model_weight: ./ckpt/litevae_baseline_kvasir-instrument_correct_transforms/epochs_1000/checkpoints/best_valid_loss_rec_736.pth
# snapshot_path: ./ckpt/litevae_baseline_kvasir-instrument_correct_transforms/epochs_1000/valid_busi_best_valid_loss_rec
# save_seg_img_path: ./ckpt/litevae_baseline_kvasir-instrument_correct_transforms/epochs_1000/predicted_masks_best_valid_loss_rec

model_weight: ./ckpt/provided_models/kvasir-instrument/best_model.pth #./ckpt/litevae_baseline_busi_correct_transforms/epochs_1000/checkpoints/best_valid_loss_rec_349.pth
snapshot_path: ./ckpt/provided_models/kvasir-instrument/sd-vae_valid_busi_best_model # ./ckpt/litevae_baseline_busi_correct_transforms/epochs_1000/valid_busi_best_valid_loss_rec
save_seg_img_path: ./ckpt/provided_models/kvasir-instrument/sd-vae_predicted_masks_best_model # ./ckpt/litevae_baseline_busi_correct_transforms/epochs_1000/predicted_masks_best_valid_loss_rec

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# loss_rec Settings
w_rec: 1
